config/routes.rb
CarTalk::Application.routes.draw do
  get "info_pages/home"

  get "info_pages/help"

  get "info_pages/about"

  get "users/new"

  resources :sessions
  resources :info_pages
  root :to => redirect('/info_pages/home')
  resources :cars
  root :to => redirect('/cars')
  resources :users
  root :to => redirect('/users')
  match ':controller(/:action(/:id))(.:format)'
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :name,   :presence => true,
  :length          => { :maximum => 50 }

  validates :email,  :presence => true,
  :format          => { :with => email_regex },
  :uniqueness      => { :case_sensitive => false }

  validates :password,  :presence => true,
  :confirmation    => true,
  :length          => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)

    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private
  def encrypt_password
    self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
    self.encrypted_password = encrypt(password)
  end
  def encrypt(pass)
    Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
  def show
    id = params[:id] # retrieve car ID from URI route
    @car = Car.find(id) # look up car by unique ID
    # will render app/views/cars/show.html.haml by default
  end
  def new
    # default: render 'new' template
  end
  def create
    @car = Car.create!(params[:car])
    flash[:notice] = "#{@car.make} #{@car.model} was successfully created."
    redirect_to cars_path
  end
  def edit
    @car = Car.find params[:id]
  end
  def update
    @car = Car.find params[:id]
    @car.update_attributes!(params[:car])
    flash[:notice] = "#{@car.make} #{@car.model} was successfully updated."
    redirect_to car_path(@car)
  end
  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    flash[:notice] = "#{@car.make} #{@car.model} was successfully deleted."
    redirect_to cars_path
  end
end

app/controllers/info_pages_controller.rb
class InfoPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])

    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      render :new
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      # render :text => "here"
      render action: "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_pages_helper.rb
module InfoPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/edit.html.haml
%h2 Edit Car

= form_tag cars_path,  :method => :post do

  = label :car, :make, 'Make'
  = text_field :car, :make

  = label :car, :model, 'Model'
  = text_field :car, :model

  = label :car, :year, 'Year'
  = text_field :car, :year

  = label :car, :body, 'Body Type'
  = text_field :car, :body

  = label :car, :avg_price, 'Average Price'
  = text_field :car, :avg_price

  = label :car, :comments, 'Additional Comments'
  = text_field :car, :comments

  = submit_tag 'Save Changes'

app/views/cars/index.html.haml
-# This file is app/views/cars/index.html.haml
%h1 All Cars

%table#cars
  %thead
    %tr
      %th Make
      %th Model
      %th Year
      %th Type
      %th More Info
  %tbody
    - @cars.each do |car|
      %tr
        %td= car.make
        %td= car.model
        %td= car.year
        %td= car.body
        %td= link_to "More about #{car.make} #{car.model}", car_path(car)
  
= link_to 'Add new car', new_car_path
= link_to 'Sign up', new_user_path
= link_to 'Sign in', new_session_path
= link_to 'Back to home', info_pages_home_path
= link_to 'About us', info_pages_about_path
= link_to 'Help', info_pages_help_path

app/views/cars/new.html.haml
%h2 Upload New Car

= form_tag cars_path, :method => :post do

  = label :car, :make, 'Make'
  = text_field :car, :make

  = label :car, :model, 'Model'
  = text_field :car, :model
  
  = label :car, :year, 'Year'
  = text_field :car, :year

  = label :car, :body, 'Body Type'
  = text_field :car, :body

  = label :car, :avg_price, 'Average Price'
  = text_field :car, :avg_price

  = label :car, :comments, 'Additional comments'
  = text_field :car, :comments

  = submit_tag 'Save Changes'

app/views/cars/show.html.haml
%h2 Details about #{@car.title}

%ul#details
  %li 
     Body Type:
     = @car.body
  
%h3 Comments:

%p#comments = @car.comments

= link_to 'Back to car list', cars_path

app/views/info_pages/about.html.haml
%h1 About Us!
%p This website was developed with a simple goal in mind:
to unite people who share a common interest.

=image_tag asset_path('Fast_cars.gif')
= link_to 'Back Home', info_pages_home_path
= link_to 'Help', info_pages_help_path

app/views/info_pages/help.html.haml
%h1 Help!
%p This page will be used for help purposes.

=image_tag asset_path('Fast_cars.gif')
= link_to 'Back Home', info_pages_home_path

app/views/info_pages/home.html.haml
%h1 Welcome to Car Talk!
%p A place for the car enthusiast in you!
%p To begin, either sign in, sign up, or view cars.

=image_tag asset_path('Fast_cars.gif')
%p
= button_to 'Sign up', new_user_path
= button_to 'Sign in', new_session_path
= link_to 'View cars', cars_path
= link_to 'About us', info_pages_about_path
= link_to 'Help', info_pages_help_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Car Talk!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    
    %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning] 
    = yield

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h1>User <%= @user.id %> </h1>